// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using vpp_global.Api.Data;

#nullable disable

namespace vpp_global.Api.Migrations
{
    [DbContext(typeof(VppDbContext))]
    [Migration("20260915082814_AccumulatorRampModel")]
    partial class AccumulatorRampModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AccumulatorModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("CapacityKwh")
                        .HasColumnType("double precision");

                    b.Property<string>("Chemistry")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("MaxChargeKw")
                        .HasColumnType("double precision");

                    b.Property<double>("MaxDepthOfDischargePercent")
                        .HasColumnType("double precision");

                    b.Property<double>("MaxDischargeKw")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("RampRateKwPerHour")
                        .HasColumnType("double precision");

                    b.Property<int>("RatedCycleLife")
                        .HasColumnType("integer");

                    b.Property<double>("RoundTripEfficiencyPercent")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("AccumulatorModel");
                });

            modelBuilder.Entity("ConsumerModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsControllable")
                        .HasColumnType("boolean");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("RatedPowerKw")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("ConsumerModel");
                });

            modelBuilder.Entity("Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<int>("HomeSystemId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Devices");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Device");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("GeneratorModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("EfficiencyPercent")
                        .HasColumnType("double precision");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("RatedCapacityKw")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("GeneratorModel");
                });

            modelBuilder.Entity("GridNode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RegionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.ToTable("GridNodes");
                });

            modelBuilder.Entity("HomeSystem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GridNodeId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("highPrice")
                        .HasColumnType("double precision");

                    b.Property<double>("lowPrice")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("GridNodeId");

                    b.ToTable("HomeSystems");
                });

            modelBuilder.Entity("InverterModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("EfficiencyPercent")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsHybrid")
                        .HasColumnType("boolean");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("MaxDcInputKw")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("RatedPowerKw")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("InverterModels");
                });

            modelBuilder.Entity("PowerReading", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("DeviceId")
                        .HasColumnType("integer");

                    b.Property<int?>("GridNodeId")
                        .HasColumnType("integer");

                    b.Property<double>("PowerKw")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("PowerReadings");
                });

            modelBuilder.Entity("PowerSpectrum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("DeviceId")
                        .HasColumnType("integer");

                    b.Property<int?>("GridNodeId")
                        .HasColumnType("integer");

                    b.Property<double>("MeanPowerKw")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("ReferenceTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId")
                        .IsUnique();

                    b.HasIndex("GridNodeId")
                        .IsUnique();

                    b.ToTable("PowerSpectra");
                });

            modelBuilder.Entity("Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Regions");
                });

            modelBuilder.Entity("Simulation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowNegative")
                        .HasColumnType("boolean");

                    b.Property<double>("AmplitudeKw")
                        .HasColumnType("double precision");

                    b.Property<int?>("DeviceId")
                        .HasColumnType("integer");

                    b.Property<int?>("GridNodeId")
                        .HasColumnType("integer");

                    b.Property<double>("MeanKw")
                        .HasColumnType("double precision");

                    b.Property<double>("NoiseStdDevKw")
                        .HasColumnType("double precision");

                    b.Property<double>("PeriodHours")
                        .HasColumnType("double precision");

                    b.Property<double>("PhaseShift")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("GridNodeId");

                    b.ToTable("Simulations");
                });

            modelBuilder.Entity("SpectralComponent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("AmplitudeKw")
                        .HasColumnType("double precision");

                    b.Property<double>("PeriodHours")
                        .HasColumnType("double precision");

                    b.Property<double>("PhaseRadians")
                        .HasColumnType("double precision");

                    b.Property<int>("PowerSpectrumId")
                        .HasColumnType("integer");

                    b.Property<double>("SignificanceScore")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("PowerSpectrumId");

                    b.ToTable("SpectralComponents");
                });

            modelBuilder.Entity("Accumulator", b =>
                {
                    b.HasBaseType("Device");

                    b.Property<double>("CapacityKWH")
                        .HasColumnType("double precision");

                    b.Property<double>("CurrentChargeKWH")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("LastTickAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ModelId")
                        .HasColumnType("integer");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<double>("appliedCurrentKw")
                        .HasColumnType("double precision");

                    b.Property<double>("lowKWH")
                        .HasColumnType("double precision");

                    b.Property<double>("maxKWH")
                        .HasColumnType("double precision");

                    b.Property<double>("minKWH")
                        .HasColumnType("double precision");

                    b.Property<double>("targetCurrentKw")
                        .HasColumnType("double precision");

                    b.HasIndex("ModelId");

                    b.ToTable("Devices", t =>
                        {
                            t.Property("ModelId")
                                .HasColumnName("Accumulator_ModelId");
                        });

                    b.HasDiscriminator().HasValue("Accumulator");
                });

            modelBuilder.Entity("Consumer", b =>
                {
                    b.HasBaseType("Device");

                    b.Property<int>("ModelId")
                        .HasColumnType("integer");

                    b.HasIndex("HomeSystemId");

                    b.HasIndex("ModelId");

                    b.HasDiscriminator().HasValue("Consumer");
                });

            modelBuilder.Entity("Generator", b =>
                {
                    b.HasBaseType("Device");

                    b.Property<int>("ModelId")
                        .HasColumnType("integer");

                    b.HasIndex("HomeSystemId");

                    b.HasIndex("ModelId");

                    b.ToTable("Devices", t =>
                        {
                            t.Property("ModelId")
                                .HasColumnName("Generator_ModelId");
                        });

                    b.HasDiscriminator().HasValue("Generator");
                });

            modelBuilder.Entity("Inverter", b =>
                {
                    b.HasBaseType("Device");

                    b.Property<double>("InverterCurrent")
                        .HasColumnType("double precision");

                    b.Property<int>("InverterMode")
                        .HasColumnType("integer");

                    b.Property<double>("MaxDCInput")
                        .HasColumnType("double precision");

                    b.Property<double>("MaxOutputPower")
                        .HasColumnType("double precision");

                    b.Property<int>("ModelId")
                        .HasColumnType("integer");

                    b.Property<double>("ac2dcEfficiency")
                        .HasColumnType("double precision");

                    b.Property<double>("dc2acEfficiency")
                        .HasColumnType("double precision");

                    b.Property<bool>("onAcc")
                        .HasColumnType("boolean");

                    b.Property<bool>("onGrid")
                        .HasColumnType("boolean");

                    b.HasIndex("HomeSystemId");

                    b.HasIndex("ModelId");

                    b.ToTable("Devices", t =>
                        {
                            t.Property("ModelId")
                                .HasColumnName("Inverter_ModelId");
                        });

                    b.HasDiscriminator().HasValue("Inverter");
                });

            modelBuilder.Entity("Battery", b =>
                {
                    b.HasBaseType("Accumulator");

                    b.Property<string>("Chemistry")
                        .HasColumnType("text");

                    b.HasIndex("HomeSystemId");

                    b.ToTable("Devices", t =>
                        {
                            t.Property("ModelId")
                                .HasColumnName("Accumulator_ModelId");
                        });

                    b.HasDiscriminator().HasValue("Battery");
                });

            modelBuilder.Entity("EV", b =>
                {
                    b.HasBaseType("Accumulator");

                    b.Property<string>("LicensePlate")
                        .HasColumnType("text");

                    b.HasIndex("HomeSystemId");

                    b.ToTable("Devices", t =>
                        {
                            t.Property("ModelId")
                                .HasColumnName("Accumulator_ModelId");
                        });

                    b.HasDiscriminator().HasValue("EV");
                });

            modelBuilder.Entity("SolarPowerPlant", b =>
                {
                    b.HasBaseType("Generator");

                    b.Property<int>("AzimuthDegrees")
                        .HasColumnType("integer");

                    b.Property<int>("TiltDegrees")
                        .HasColumnType("integer");

                    b.Property<double>("TotalPanelAreaM2")
                        .HasColumnType("double precision");

                    b.ToTable("Devices", t =>
                        {
                            t.Property("ModelId")
                                .HasColumnName("Generator_ModelId");
                        });

                    b.HasDiscriminator().HasValue("SolarPowerPlant");
                });

            modelBuilder.Entity("WindPowerPlant", b =>
                {
                    b.HasBaseType("Generator");

                    b.Property<double>("CutInWindSpeedMs")
                        .HasColumnType("double precision");

                    b.Property<double>("RotorDiameterM")
                        .HasColumnType("double precision");

                    b.ToTable("Devices", t =>
                        {
                            t.Property("ModelId")
                                .HasColumnName("Generator_ModelId");
                        });

                    b.HasDiscriminator().HasValue("WindPowerPlant");
                });

            modelBuilder.Entity("GridNode", b =>
                {
                    b.HasOne("Region", "Region")
                        .WithMany("GridNodes")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("HomeSystem", b =>
                {
                    b.HasOne("GridNode", "GridNode")
                        .WithMany("HomeSystems")
                        .HasForeignKey("GridNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GridNode");
                });

            modelBuilder.Entity("PowerSpectrum", b =>
                {
                    b.HasOne("Device", "Device")
                        .WithOne("PowerSpectrum")
                        .HasForeignKey("PowerSpectrum", "DeviceId");

                    b.HasOne("GridNode", "GridNode")
                        .WithOne("PowerSpectrum")
                        .HasForeignKey("PowerSpectrum", "GridNodeId");

                    b.Navigation("Device");

                    b.Navigation("GridNode");
                });

            modelBuilder.Entity("Simulation", b =>
                {
                    b.HasOne("Device", "Device")
                        .WithMany("Simulations")
                        .HasForeignKey("DeviceId");

                    b.HasOne("GridNode", "GridNode")
                        .WithMany("Simulations")
                        .HasForeignKey("GridNodeId");

                    b.Navigation("Device");

                    b.Navigation("GridNode");
                });

            modelBuilder.Entity("SpectralComponent", b =>
                {
                    b.HasOne("PowerSpectrum", "PowerSpectrum")
                        .WithMany("Components")
                        .HasForeignKey("PowerSpectrumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PowerSpectrum");
                });

            modelBuilder.Entity("Accumulator", b =>
                {
                    b.HasOne("AccumulatorModel", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Model");
                });

            modelBuilder.Entity("Consumer", b =>
                {
                    b.HasOne("HomeSystem", "HomeSystem")
                        .WithMany("Consumers")
                        .HasForeignKey("HomeSystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConsumerModel", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HomeSystem");

                    b.Navigation("Model");
                });

            modelBuilder.Entity("Generator", b =>
                {
                    b.HasOne("HomeSystem", "HomeSystem")
                        .WithMany("Generators")
                        .HasForeignKey("HomeSystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GeneratorModel", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HomeSystem");

                    b.Navigation("Model");
                });

            modelBuilder.Entity("Inverter", b =>
                {
                    b.HasOne("HomeSystem", "HomeSystem")
                        .WithMany()
                        .HasForeignKey("HomeSystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InverterModel", "InverterModel")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HomeSystem");

                    b.Navigation("InverterModel");
                });

            modelBuilder.Entity("Battery", b =>
                {
                    b.HasOne("HomeSystem", "HomeSystem")
                        .WithMany("Batteries")
                        .HasForeignKey("HomeSystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HomeSystem");
                });

            modelBuilder.Entity("EV", b =>
                {
                    b.HasOne("HomeSystem", "HomeSystem")
                        .WithMany("EVs")
                        .HasForeignKey("HomeSystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HomeSystem");
                });

            modelBuilder.Entity("Device", b =>
                {
                    b.Navigation("PowerSpectrum");

                    b.Navigation("Simulations");
                });

            modelBuilder.Entity("GridNode", b =>
                {
                    b.Navigation("HomeSystems");

                    b.Navigation("PowerSpectrum");

                    b.Navigation("Simulations");
                });

            modelBuilder.Entity("HomeSystem", b =>
                {
                    b.Navigation("Batteries");

                    b.Navigation("Consumers");

                    b.Navigation("EVs");

                    b.Navigation("Generators");
                });

            modelBuilder.Entity("PowerSpectrum", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("Region", b =>
                {
                    b.Navigation("GridNodes");
                });
#pragma warning restore 612, 618
        }
    }
}
